name: Sync Folders

on:
  push:
    paths:
      - "First_folder/**"
  workflow_dispatch:
    # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Debug - List files before sync
        run: |
          echo "Files in First_folder:"
          ls -la First_folder/
          echo "Files in Second_folder (if it exists):"
          ls -la Second_folder/ || echo "Second_folder does not exist yet"

      - name: Sync First_folder to Second_folder
        run: |
          # Create Second_folder if it doesn't exist
          if [ ! -d "Second_folder" ]; then
            mkdir Second_folder
            echo "Created Second_folder directory"
          else
            echo "Second_folder already exists"
          fi

          # Clear the Second_folder to handle deletions
          echo "Clearing Second_folder to handle deleted files"
          rm -rf Second_folder/*

          # Copy all files from First_folder to Second_folder
          echo "Copying files from First_folder to Second_folder"
          if [ "$(ls -A First_folder 2>/dev/null)" ]; then
            cp -Rv First_folder/* Second_folder/ || true
          else
            echo "First_folder is empty, nothing to copy"
          fi

          # List files after copy
          echo "Files in Second_folder after copy:"
          ls -la Second_folder/

          # Check if there are any changes
          if git diff --quiet Second_folder; then
            echo "No changes to commit"
            exit 0
          else
            echo "Changes detected in Second_folder"
            git diff Second_folder
          fi

          # Configure Git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Add, commit and push changes
          echo "Committing and pushing changes"
          git add Second_folder/
          git commit -m "Sync: Update Second_folder with changes from First_folder"
          git push origin main
          echo "Sync completed successfully"
