name: Sync Folders

on:
  push:
    paths:
      - "First_folder/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Sync First_folder to Second_folder
        run: |
          mkdir -p Second_folder

          echo "Syncing files from First_folder to Second_folder..."
          rsync -av --delete First_folder/ Second_folder/

          echo "Deleting contents of First_folder after sync..."
          rm -rf First_folder/*

          echo "Checking for changes..."
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add Second_folder/ First_folder/
          git commit -m "Sync: Updated Second_folder and cleared First_folder"
          git push origin main

          echo "Sync completed."
